//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbCrudEntities1 : DbContext
    {
        public DbCrudEntities1()
            : base("name=DbCrudEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Case1> Case1 { get; set; }
        public virtual DbSet<Case2> Case2 { get; set; }
        public virtual DbSet<Case3> Case3 { get; set; }
    
        public virtual ObjectResult<SP_GetCase1_Result> SP_GetCase1(string age, Nullable<int> pageno, Nullable<int> pagesize)
        {
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var pagenoParameter = pageno.HasValue ?
                new ObjectParameter("pageno", pageno) :
                new ObjectParameter("pageno", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCase1_Result>("SP_GetCase1", ageParameter, pagenoParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<SP_GetCase2_Result> SP_GetCase2(string age, Nullable<int> pageno, Nullable<int> pagesize)
        {
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var pagenoParameter = pageno.HasValue ?
                new ObjectParameter("pageno", pageno) :
                new ObjectParameter("pageno", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCase2_Result>("SP_GetCase2", ageParameter, pagenoParameter, pagesizeParameter);
        }
    
        public virtual ObjectResult<SP_GetCase3_Result> SP_GetCase3(string age, Nullable<int> pageno, Nullable<int> pagesize)
        {
            var ageParameter = age != null ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(string));
    
            var pagenoParameter = pageno.HasValue ?
                new ObjectParameter("pageno", pageno) :
                new ObjectParameter("pageno", typeof(int));
    
            var pagesizeParameter = pagesize.HasValue ?
                new ObjectParameter("pagesize", pagesize) :
                new ObjectParameter("pagesize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCase3_Result>("SP_GetCase3", ageParameter, pagenoParameter, pagesizeParameter);
        }
    }
}
